name: Clean, De-duplicate and Wrap Address List

on:
  push:
    branches:
      - main  # Замените на master, если ваша ветка называется так
    paths:
      - 'source.list'

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Process file
        run: |
          # 1. Удаляем комментарии, пустые строки и оглавление с помощью sed
          # 2. Удаляем дубликаты с сохранением порядка строк с помощью awk
          # 3. Оборачиваем результат в server=/ и /127.0.0.1#5353 с помощью sed
          sed -e '/^#/d' -e '/^$/d' -e '/^[A-Za-z]$/d' source.list | \
          awk '!seen[$0]++' | \
          sed -e 's/^/server=\//' -e 's/$/\/127.0.0.1#5353/' > addresses.list

      - name: Commit and Push cleaned file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add addresses.list
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-clean, de-duplicate and wrap address list" && git push)
